#!/usr/bin/env bash
# scaffold.sh — run once at project root after `npm create vite@latest . -- --template react-ts`
set -e

echo "📦 Installing dependencies..."

npm install \
  @reduxjs/toolkit \
  react-redux \
  @tanstack/react-router \
  @tanstack/router-devtools \
  zod \
  @sentry/react \
  styled-components

npm install -D \
  @tanstack/router-plugin \
  @tanstack/router-cli \
  @types/react \
  @types/react-dom \
  @types/styled-components \
  vite-tsconfig-paths

echo "🗂  Creating folder structure..."

# ── app ────────────────────────────────────────────────────────────────────
mkdir -p src/app/api

cat > src/app/store.ts << 'EOF'
import { configureStore } from '@reduxjs/toolkit';
import { baseApi } from './api/baseApi';

export const store = configureStore({
  reducer: {
    [baseApi.reducerPath]: baseApi.reducer,
    // feature slices go here
  },
  middleware: (getDefaultMiddleware) =>
    getDefaultMiddleware().concat(baseApi.middleware),
});

export type RootState = ReturnType<typeof store.getState>;
export type AppDispatch = typeof store.dispatch;
EOF

cat > src/app/api/baseApi.ts << 'EOF'
import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

export const baseApi = createApi({
  reducerPath: 'api',
  baseQuery: fetchBaseQuery({ baseUrl: '/api' }),
  endpoints: () => ({}),
});
EOF

cat > src/app/router.tsx << 'EOF'
import { createRouter } from '@tanstack/react-router';
import { routeTree } from '../routes/routeTree.gen'; // generated by TanStack Router CLI

export const router = createRouter({ routeTree });

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}
EOF

# ── routes ──────────────────────────────────────────────────────────────────
mkdir -p src/routes

cat > src/routes/__root.tsx << 'EOF'
import { createRootRoute, Outlet } from '@tanstack/react-router';

export const Route = createRootRoute({
  component: () => <Outlet />,
});
EOF

cat > src/routes/index.tsx << 'EOF'
import { createFileRoute } from '@tanstack/react-router';

export const Route = createFileRoute('/')({
  component: () => <div>Home</div>,
});
EOF

# ── providers ───────────────────────────────────────────────────────────────
mkdir -p src/providers

cat > src/providers/AppProviders.tsx << 'EOF'
import { Provider } from 'react-redux';
import { RouterProvider } from '@tanstack/react-router';
import { ThemeProvider } from 'styled-components';
import { store } from '../app/store';
import { router } from '../app/router';
import { theme } from './theme';
import { GlobalStyles } from './GlobalStyles';

export function AppProviders() {
  return (
    <Provider store={store}>
      <ThemeProvider theme={theme}>
        <GlobalStyles />
        <RouterProvider router={router} />
      </ThemeProvider>
    </Provider>
  );
}
EOF

cat > src/providers/theme.ts << 'EOF'
export const theme = {
  colors: {
    primary: '#4F46E5',
    secondary: '#7C3AED',
    background: '#F9FAFB',
    surface: '#FFFFFF',
    text: '#111827',
    textMuted: '#6B7280',
    border: '#E5E7EB',
    error: '#EF4444',
    success: '#10B981',
  },
  spacing: {
    xs: '4px',
    sm: '8px',
    md: '16px',
    lg: '24px',
    xl: '32px',
    xxl: '48px',
  },
  borderRadius: {
    sm: '4px',
    md: '8px',
    lg: '12px',
    full: '9999px',
  },
  fontSize: {
    sm: '12px',
    md: '14px',
    lg: '16px',
    xl: '20px',
    xxl: '24px',
  },
} as const;

export type AppTheme = typeof theme;
EOF

cat > src/providers/GlobalStyles.ts << 'EOF'
import { createGlobalStyle } from 'styled-components';

export const GlobalStyles = createGlobalStyle`
  *, *::before, *::after {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
  }

  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    background-color: ${({ theme }) => theme.colors.background};
    color: ${({ theme }) => theme.colors.text};
    font-size: ${({ theme }) => theme.fontSize.md};
  }
`;
EOF

# ── styled-components theme type augmentation ─────────────────────────────────
mkdir -p src/types

cat > src/types/styled.d.ts << 'EOF'
import { AppTheme } from '../providers/theme';

declare module 'styled-components' {
  export interface DefaultTheme extends AppTheme {}
}
EOF

# ── common ───────────────────────────────────────────────────────────────────
mkdir -p src/common/components
mkdir -p src/common/hooks
mkdir -p src/common/constants

touch src/common/components/.gitkeep
touch src/common/hooks/.gitkeep
touch src/common/constants/index.ts

# ── hooks (app-level) ────────────────────────────────────────────────────────
mkdir -p src/hooks
touch src/hooks/.gitkeep

# ── utils (app-level) ────────────────────────────────────────────────────────
mkdir -p src/utils
touch src/utils/.gitkeep

# ── features ─────────────────────────────────────────────────────────────────
# Creates a scaffold for one example feature. Duplicate this pattern per feature.
FEATURE="example"
mkdir -p src/features/$FEATURE/{hooks,components,widgets,state,types,utils,constants}

cat > src/features/$FEATURE/hooks/use${FEATURE^}.ts << 'EOF'
// Discriminated union state — all hooks must follow this pattern
type ExampleState =
  | { status: 'loading' }
  | { status: 'error'; error: Error }
  | { status: 'success'; data: unknown[] };

export function useExample(): ExampleState {
  // call RTK Query here, map to discriminated union
  return { status: 'loading' };
}
EOF

cat > src/features/$FEATURE/widgets/ExampleWidget.tsx << 'EOF'
import styled from 'styled-components';
import { useExample } from '../hooks/useExample';

const StyledWrapper = styled.div`
  padding: ${({ theme }) => theme.spacing.md};
  border-radius: ${({ theme }) => theme.borderRadius.md};
  background: ${({ theme }) => theme.colors.surface};
`;

// Pure UI — Storybook targets this export
export function ExampleWidgetContent(props: ReturnType<typeof useExample>) {
  if (props.status === 'loading') return <StyledWrapper>Loading…</StyledWrapper>;
  if (props.status === 'error') return <StyledWrapper>Error: {props.error.message}</StyledWrapper>;
  return <StyledWrapper>Data: {JSON.stringify(props.data)}</StyledWrapper>;
}

// Container — calls hook, passes state down. Nothing else.
export function ExampleWidget() {
  const state = useExample();
  return <ExampleWidgetContent {...state} />;
}
EOF

cat > src/features/$FEATURE/types/types.ts << 'EOF'
import { z } from 'zod';

export const ExampleSchema = z.object({
  id: z.string(),
});

export type Example = z.infer<typeof ExampleSchema>;
EOF

cat > src/features/$FEATURE/index.ts << 'EOF'
// Public surface of the example feature
export { ExampleWidget, ExampleWidgetContent } from './widgets/ExampleWidget';
EOF

# ── main entry ───────────────────────────────────────────────────────────────
cat > src/main.tsx << 'EOF'
import React from 'react';
import ReactDOM from 'react-dom/client';
import { AppProviders } from './providers/AppProviders';

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <AppProviders />
  </React.StrictMode>
);
EOF

echo ""
echo "✅ Done! Structure created:"
echo ""
find src -type f | sort
echo ""
echo "Next steps:"
echo "  1. Copy CLAUDE.md to your project root"
echo "  2. Run: npx @tanstack/router-cli generate  (to generate routeTree.gen.ts)"
echo "  3. Duplicate src/features/example/ for each real feature"
